sudo: required

language: node_js

node_js: '0.10'
  
services:
  - docker
  - elasticsearch

branches:
  only:
  - master

before_install:
  - docker build -t hmda/loader .

script:
  - docker run --rm hmda/loader npm test
